export * from './avales.entity'
export * from './business.entity'
export * from './catalogue.entity'
export * from './civil-status.entity'
export * from './customer.entity'
export * from './employees.entity'
export * from './housing-type.entity'
export * from './personal-reference.entity'